name: build-i3

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: i3

      - name: Cargo check
        run: cargo check --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: i3

      - name: Cargo test
        run: cargo test --verbose

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: i3
    - name: Build
      run: cargo build --verbose
