name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Cargo check
        run: cargo check --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Cargo test
        run: cargo test --verbose

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: actions/checkout@v1
      run: cargo build --verbose

  release-build:
    name: Release Build
    runs-on: ubuntu-latest
    needs: [check, test, build]

    steps:
    - name: Build
      uses: actions/checkout@v1
      run: cargo build --release --verbose
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: binary
        path: ./target/release/sway-alttab

  publish:
    name: Publish to Cargo
    runs-on: ubuntu-latest
    needs: [check, test]

    steps:
    - name: Login
      env:
        CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: cargo login $CARGO_TOKEN

    - name: Publish
      uses: actions/checkout@v1
      run: cargo --verbose publish

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: binary
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Print tree
      shell: bash
      run: |
        echo HELLO
        tree -CAhF --dirsfirst
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: binary/sway-alttab
        asset_name: sway-alttab
        asset_content_type: application/octet-stream
